version: 2.1

orbs:
  win: circleci/windows@2.2.0

commands:
  pull_submodules:
    steps:
      - run :
          name: Pull submodules
          command: |
            git submodule init
            git submodule update --remote

  install_build_deps:
    parameters:
      sudo:
        type: boolean
        default: false
      extra:
        type: string
        default: ""
    steps:
      - run:
          name: install cmake gcc python3
          command: |
            <<#parameters.sudo >> sudo <</parameters.sudo >> apt-get update
            <<#parameters.sudo >> sudo <</parameters.sudo >> apt-get install \
            -y cmake g++ python3 python3-pip git << parameters.extra >>
      - run:
          name: install fmtlib
          command: |
            git clone https://github.com/fmtlib/fmt.git
            mkdir fmt/build
            cd fmt/build
            cmake -DFMT_TEST=OFF -DFMT_DOC=OFF ..
            make
            <<#parameters.sudo >> sudo <</parameters.sudo >> make install
      - run:
          name: install layered-file-protocol
          command: |
            git clone https://github.com/equinor/layered-file-protocols.git
            mkdir layered-file-protocols/build
            cd layered-file-protocols/build
            cmake -DBUILD_SHARED_LIBS=ON \
                  -DLFP_FMT_HEADER_ONLY=ON \
                  -DBUILD_TESTING=OFF \
                  -DCMAKE_BUILD_TYPE=Release ..
            make
            <<#parameters.sudo >> sudo <</parameters.sudo >> make install

  python_build:
    parameters:
      docs:
        type: string
        default: ""
    steps:
      - checkout
      - install_build_deps:
          sudo: true
      - pull_submodules
      - run:
          name: install core
          command: |
            mkdir build
            cd build
            cmake -DBUILD_SHARED_LIBS=ON \
                  -DCMAKE_BUILD_TYPE=Release \
                  -DBUILD_TESTING=OFF \
                  -DBUILD_PYTHON=OFF \
                   << parameters.docs >> \
                  ..
            make
            sudo make install
            sudo ldconfig /usr/local/lib
            echo "export mpark_DIR=$PWD/external/mpark" >> $BASH_ENV
      - run:
          name: install python dependencies
          command: python -m pip install --user -r python/requirements-dev.txt
      - run:
          name: build python
          command: |
            cd python
            python setup.py build_ext --inplace install --user test

  cmake_build:
    description: dlisio build steps
    parameters:
      type:
        description: build type
        type: enum
        default: Release
        enum: ["Release", "Debug", "RelWithDebInfo"]
      scan:
        description: scan-build or similar command prefix
        type: string
        default: ""
    steps:
      - run:
          name: install python extra
          command: python3 -m pip install --user -r python/requirements-dev.txt
      - run:
          name: configure
          command: |
            mkdir build
            cd build
            << parameters.scan >> \
            cmake -DBUILD_SHARED_LIBS=ON \
                  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
                  -DCMAKE_BUILD_TYPE=<< parameters.type >> \
                  -DPYTHON_EXECUTABLE=`which python3` \
                  ..
      - run:
          name: build and install
          command: << parameters.scan >> cmake --build build --target install
      - run:
          name: test
          command: |
            cd build
            ctest --output-on-failure

  windows_build:
    description: building on windows
    parameters:
      python_version:
        description: python version
        type: string
      arch:
        description: x86 or x64
        type: enum
        enum: ["x86", "x64"]
    steps:
      # CircleCI machine is 64 bit, but in theory this script sets everything explicitly
      - run:
          name: Explicitly disable autocrlf
          # if not executed, our binary files  will be changed
          command: |
            git config --global core.autocrlf false
      - checkout
#       - restore_cache:
#           key: vers1-<< parameters.python_version >>-<< parameters.arch >>
#       - run:
#           name: get packages list
#           command: |
#             Get-Package
#       - run:
#           name: install python #TODO: cache, but per version
#           command: |
#             $choco_options = ''
#             if('<< parameters.arch >>' -eq 'x86') {
#               $choco_options = '--forcex86'
#             }
#             #choco install python3 --version=<< parameters.python_version >> --no-progress --install-arguments="PrependPath=1"  $choco_options
#             choco install python3 --version=<< parameters.python_version >> --no-progress --install-arguments '"/l*v c:\python3_msi_install.log"'
#             refreshenv # to remove
#       - run:
#           name: refreshevn in separate step
#           command: |
#             refreshenv
#       - run:
#           name: install python #TODO: cache, but per version
#           command: |
#             $choco_options = ''
#             if('<< parameters.arch >>' -eq 'x86') {
#               $choco_options = '--forcex86'
#             }
#             choco install python3 --version=<< parameters.python_version >> --no-progress --install-arguments="PrependPath=1"  $choco_options
      - run:
          name: activate correct version with miniconda?
          command: |
            conda init powershell
            $Env:CONDA_FORCE_32BIT = 1
            conda create -y -n py38_32 python=3.8
      - run:
          name: install python packages #TODO: cache per version?
          command: |
            python --version
            conda activate py38_32
            python --version
            python -c "import struct;print(struct.calcsize('P') * 8)"
            python -m pip install --upgrade pip
            python -m pip install --upgrade setuptools
            python -m pip install --upgrade certifi
            refreshenv
      - run:
          name: install cmake #TODO: cache
          command: |
            choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --no-progress
            refreshenv
#       - save_cache:
#           key: vers1-<< parameters.python_version >>-<< parameters.arch >>
#           paths:
#             C:\ProgramData\chocolatey
      - restore_cache:
          key: vers1-vcpkg
      - run:
          name: install fmt and vcpkg #TODO: cache
          command: |
            if (!(Test-Path "C:/Users/circleci/project/vcpkg")){
                git clone https://github.com/Microsoft/vcpkg.git
                cd vcpkg
                .\bootstrap-vcpkg.bat
                .\vcpkg install fmt:<< parameters.arch >>-windows
            }
      - save_cache:
          key: vers1-vcpkg
          paths:
            C:/Users/circleci/project/vcpkg 
      - run:
          name: install layered-file-protocol
          command: |
            git clone https://github.com/equinor/layered-file-protocols.git
            mkdir layered-file-protocols/build
            cd layered-file-protocols/build
            if('<< parameters.arch >>' -eq 'x86') {
              $platform = 'Win32'
            } else {
              $platform = 'x64'
            }
            cmake -DCMAKE_CXX_FLAGS="/D_CRT_SECURE_NO_WARNINGS /EHsc" `
                  -DLFP_FMT_HEADER_ONLY=ON `
                  -DBUILD_TESTING=OFF `
                  -DCMAKE_BUILD_TYPE=Release `
                  -A $platform `
                  -DVCPKG_TARGET_TRIPLET=<< parameters.arch >>-windows `
                  -DCMAKE_TOOLCHAIN_FILE=C:/Users/circleci/project/vcpkg/scripts/buildsystems/vcpkg.cmake ..
            cmake --build . --config Release --target install     
      - pull_submodules
      - run:
          name: install python dependencies
          command: |
            python --version
            conda activate py38_32
            python --version
            python -c "import struct;print(struct.calcsize('P') * 8)"
            python -m pip install --user -r python/requirements-dev.txt
            refreshenv
      - run:
          name: install core
          environment:
            lfp_DIR: "C:/Program Files (x86)/layered-file-protocols/share/lfp/cmake"
          command: |
            mkdir build
            cd build
            if('<< parameters.arch >>' -eq 'x86') {
              $platform = 'Win32'
            } else {
              $platform = 'x64'
            }
            python --version
            conda activate py38_32
            python --version
            python -c "import struct;print(struct.calcsize('P') * 8)"
            cmake -G "Visual Studio 16 2019" `
                  -DCMAKE_CXX_FLAGS="/D_CRT_SECURE_NO_WARNINGS /EHsc" `
                  -DCMAKE_BUILD_TYPE=Release `
                  -A $platform `
                  ..
            cmake --build . --target install --config Release
      - run:
          name: build python
          command: |
            cd python
            python setup.py bdist_wheel -G "Visual Studio 16 2019"

      #- store_artifacts:
      #    path: C:/Users/circleci/project/python/dist

      - persist_to_workspace:
          root: C:/Users/circleci/project/python
          paths:
            - dist/*

jobs:
  gcc:
    docker:
      - image: debian:stable
    steps:
      - checkout
      - install_build_deps
      - pull_submodules
      - cmake_build

  clang:
    docker:
      - image: debian:stable
    environment:
      CC: /usr/bin/clang
      CXX: /usr/bin/clang++
    steps:
      - checkout
      - install_build_deps:
          extra: clang
      - pull_submodules
      - cmake_build

  debug:
    docker:
      - image: debian:stable
    steps:
      - checkout
      - install_build_deps
      - pull_submodules
      - cmake_build:
          type: Debug

  scan-build:
    docker:
      - image: debian:stable
    steps:
      - checkout
      - install_build_deps:
          extra: clang clang-tools libfindbin-libs-perl
      - pull_submodules
      - cmake_build:
          scan: scan-build --status-bugs

  cppcheck:
    docker:
      - image: ubuntu:latest
    environment:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - checkout
      - install_build_deps:
          extra: cppcheck
      - pull_submodules
      - run:
          name: run cppcheck
          command: |
            cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DBUILD_TESTING=OFF
            cppcheck --enable=style,portability,performance,warning \
                     --library=posix \
                     --suppressions-list=cppcheck/suppressions.txt \
                     --inline-suppr \
                     --project=compile_commands.json \

  python-35:
    docker:
      - image: circleci/python:3.5
    steps:
      - python_build

  python-36:
    docker:
      - image: circleci/python:3.6
    steps:
      - python_build

  python-37:
    docker:
      - image: circleci/python:3.7
    steps:
      - python_build:
          docs: "-DBUILD_DOC=ON -DSPHINX_ARGS=-WT"

  python-38:
    docker:
      - image: circleci/python:3.8
    steps:
      - python_build:
          docs: "-DBUILD_DOC=ON -DSPHINX_ARGS=-WT"

  python-35-win-x86:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - windows_build:
          python_version: "3.5"
          arch: "x86"

  python-35-win-x64:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - windows_build:
          python_version: "3.5"
          arch: "x64"

  python-36-win-x86:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - windows_build:
          python_version: "3.6"
          arch: "x86"

  python-36-win-x64:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - windows_build:
          python_version: "3.6"
          arch: "x64"

  python-37-win-x86:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - windows_build:
          python_version: "3.7"
          arch: "x86"

  python-37-win-x64:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - windows_build:
          python_version: "3.7"
          arch: "x64"

  python-38-win-x86:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - windows_build:
          python_version: "3.8"
          arch: "x86"

  python-38-win-x64:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - windows_build:
          python_version: "3.8"
          arch: "x64"
          
  deploy-fake:
    docker:
      - image: debian:stable
    steps:
      - checkout
      - run:
          name: deploy step not exected to be called
          command: |
            i said you are not expected to be called

  deploy-to-test:
    docker:
      - image: circleci/python:3.7
    steps:
      - run:
          name: intall twine
          command: |
             pip install twine
      - attach_workspace:
          at: deploy            
      - run:
          name: deploy
          command: |
            cd deploy
            # everything is defined as CircleCI environemnt variables
            # TWINE_REPOSITORY and TWINE_USERNAME and TWINE_PASSWORD
            twine upload -r $TWINE_REPOSITORY -u $TWINE_USERNAME -p $TWINE_PASSWORD --skip-existing dist/*
            
workflows:
  version: 2
#   build:
#     jobs:
#       - gcc
#       - clang
#       - debug
# 
#   static-analysis:
#     jobs:
#       - cppcheck
#       - scan-build
# 
#   python:
#     jobs:
#       - python-35
#       - python-36
#       - python-37
#       - python-38
  windows:
    jobs:
#       - python-35-win-x86
#       - python-35-win-x64
#       - python-36-win-x86
#       - python-36-win-x64
#       - python-37-win-x86 #issue
#       - python-37-win-x64 #issue?
      - python-38-win-x86
#       - python-38-win-x64:
#           filters:
#             tags:
#               only: /.*/
#       - deploy-fake:
#           requires:
#             - python-38-win-x64
#           filters:
#             tags:
#               only: /[0-9]+(\.[0-9]+)*/
#             branches:
#               ignore: /.*/
#       - deploy-to-test:
#           requires:
#             - python-38-win-x64
#           filters:
#             tags:
#               only: /.*/
