name: Test bigendian

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  bigendian:
    name: Run tests on bigendian s390x system
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: .github/images/bigendian.Dockerfile
          platforms: linux/s390x

