name: Build documentation

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build_docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - uses: './.github/actions/build_core_dependencies'
        with:
          privileges: "sudo"

      - name: Install python dependencies
        run: |
            python -m pip install --upgrade pip
            python -m pip install -r python/requirements-dev.txt

      - name: Build docs
        run: |
          cmake -S . -B build          \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_TESTING=OFF        \
            -DBUILD_SHARED_LIBS=ON     \
            -DBUILD_DOC=ON
          cmake --build build
